export enum Severity {
  Error = 'error',
  Warning = 'warning',
  Info = 'info',
  Success = 'success'
}

export const heights = [
  { id: '4', label: 'Below 4ft' },
  { id: '4.0', label: '4ft 00in' },
  { id: '4.1', label: '4ft 01in' },
  { id: '4.2', label: '4ft 02in' },
  { id: '4.3', label: '4ft 03in' },
  { id: '4.4', label: '4ft 04in' },
  { id: '4.5', label: '4ft 05in' },
  { id: '4.6', label: '4ft 06in' },
  { id: '4.7', label: '4ft 07in' },
  { id: '4.8', label: '4ft 08in' },
  { id: '4.9', label: '4ft 09in' },
  { id: '4.10', label: '4ft 10in' },
  { id: '4.11', label: '4ft 11in' },
  { id: '5.0', label: '5ft 00in' },
  { id: '5.1', label: '5ft 01in' },
  { id: '5.2', label: '5ft 02in' },
  { id: '5.3', label: '5ft 03in' },
  { id: '5.4', label: '5ft 04in' },
  { id: '5.5', label: '5ft 05in' },
  { id: '5.6', label: '5ft 06in' },
  { id: '5.7', label: '5ft 07in' },
  { id: '5.8', label: '5ft 08in' },
  { id: '5.9', label: '5ft 09in' },
  { id: '5.10', label: '5ft 10in' },
  { id: '5.11', label: '5ft 11in' },
  { id: '6.0', label: '6ft 00in' },
  { id: '6.1', label: '6ft 01in' },
  { id: '6.2', label: '6ft 02in' },
  { id: '6.3', label: '6ft 03in' },
  { id: '6.4', label: '6ft 04in' },
  { id: '6.5', label: '6ft 05in' },
  { id: '6.6', label: '6ft 06in' },
  { id: '6.7', label: '6ft 07in' },
  { id: '6.8', label: '6ft 08in' },
  { id: '6.9', label: '6ft 09in' },
  { id: '6.10', label: '6ft 10in' },
  { id: '6.11', label: '6ft 11in' },
  { id: '7.0', label: '7ft 00in' },
  { id: '7', label: 'Above 7ft' }
];

export const bloodGroups = [
  { id: 'A+', label: 'A+' },
  { id: 'A-', label: 'A-' },
  { id: 'B+', label: 'B+' },
  { id: 'B-', label: 'B-' },
  { id: 'AB+', label: 'AB+' },
  { id: 'AB-', label: 'AB-' },
  { id: 'O+', label: 'O+' },
  { id: 'O-', label: 'O-' }
];

export const mobileCountryCodes = [
  { id: '+1', label: '+1', countryName: 'United States/Canada' },
  { id: '+7', label: '+7', countryName: 'Russia/Kazakhstan' },
  { id: '+20', label: '+20', countryName: 'Egypt' },
  { id: '+27', label: '+27', countryName: 'South Africa' },
  { id: '+30', label: '+30', countryName: 'Greece' },
  { id: '+31', label: '+31', countryName: 'Netherlands' },
  { id: '+32', label: '+32', countryName: 'Belgium' },
  { id: '+33', label: '+33', countryName: 'France' },
  { id: '+34', label: '+34', countryName: 'Spain' },
  { id: '+36', label: '+36', countryName: 'Hungary' },
  { id: '+39', label: '+39', countryName: 'Italy' },
  { id: '+40', label: '+40', countryName: 'Romania' },
  { id: '+41', label: '+41', countryName: 'Switzerland' },
  { id: '+43', label: '+43', countryName: 'Austria' },
  { id: '+44', label: '+44', countryName: 'United Kingdom' },
  { id: '+45', label: '+45', countryName: 'Denmark' },
  { id: '+46', label: '+46', countryName: 'Sweden' },
  { id: '+47', label: '+47', countryName: 'Norway' },
  { id: '+48', label: '+48', countryName: 'Poland' },
  { id: '+49', label: '+49', countryName: 'Germany' },
  { id: '+51', label: '+51', countryName: 'Peru' },
  { id: '+52', label: '+52', countryName: 'Mexico' },
  { id: '+53', label: '+53', countryName: 'Cuba' },
  { id: '+54', label: '+54', countryName: 'Argentina' },
  { id: '+55', label: '+55', countryName: 'Brazil' },
  { id: '+56', label: '+56', countryName: 'Chile' },
  { id: '+57', label: '+57', countryName: 'Colombia' },
  { id: '+58', label: '+58', countryName: 'Venezuela' },
  { id: '+60', label: '+60', countryName: 'Malaysia' },
  { id: '+61', label: '+61', countryName: 'Australia' },
  { id: '+62', label: '+62', countryName: 'Indonesia' },
  { id: '+63', label: '+63', countryName: 'Philippines' },
  { id: '+64', label: '+64', countryName: 'New Zealand' },
  { id: '+65', label: '+65', countryName: 'Singapore' },
  { id: '+66', label: '+66', countryName: 'Thailand' },
  { id: '+81', label: '+81', countryName: 'Japan' },
  { id: '+82', label: '+82', countryName: 'South Korea' },
  { id: '+84', label: '+84', countryName: 'Vietnam' },
  { id: '+86', label: '+86', countryName: 'China' },
  { id: '+90', label: '+90', countryName: 'Turkey' },
  { id: '+91', label: '+91', countryName: 'India' },
  { id: '+92', label: '+92', countryName: 'Pakistan' },
  { id: '+93', label: '+93', countryName: 'Afghanistan' },
  { id: '+94', label: '+94', countryName: 'Sri Lanka' },
  { id: '+95', label: '+95', countryName: 'Myanmar (Burma)' },
  { id: '+98', label: '+98', countryName: 'Iran' },
  { id: '+211', label: '+211', countryName: 'South Sudan' },
  { id: '+212', label: '+212', countryName: 'Morocco' },
  { id: '+213', label: '+213', countryName: 'Algeria' },
  { id: '+216', label: '+216', countryName: 'Tunisia' },
  { id: '+218', label: '+218', countryName: 'Libya' },
  { id: '+220', label: '+220', countryName: 'Gambia' },
  { id: '+221', label: '+221', countryName: 'Senegal' },
  { id: '+222', label: '+222', countryName: 'Mauritania' },
  { id: '+223', label: '+223', countryName: 'Mali' },
  { id: '+224', label: '+224', countryName: 'Guinea' },
  { id: '+225', label: '+225', countryName: 'Ivory Coast' },
  { id: '+226', label: '+226', countryName: 'Burkina Faso' },
  { id: '+227', label: '+227', countryName: 'Niger' },
  { id: '+228', label: '+228', countryName: 'Togo' },
  { id: '+229', label: '+229', countryName: 'Benin' },
  { id: '+230', label: '+230', countryName: 'Mauritius' },
  { id: '+231', label: '+231', countryName: 'Liberia' },
  { id: '+232', label: '+232', countryName: 'Sierra Leone' },
  { id: '+233', label: '+233', countryName: 'Ghana' },
  { id: '+234', label: '+234', countryName: 'Nigeria' },
  { id: '+235', label: '+235', countryName: 'Chad' },
  { id: '+236', label: '+236', countryName: 'Central African Republic' },
  { id: '+237', label: '+237', countryName: 'Cameroon' },
  { id: '+238', label: '+238', countryName: 'Cape Verde' },
  { id: '+239', label: '+239', countryName: 'São Tomé and Príncipe' },
  { id: '+240', label: '+240', countryName: 'Equatorial Guinea' },
  { id: '+241', label: '+241', countryName: 'Gabon' },
  { id: '+242', label: '+242', countryName: 'Congo (Brazzaville)' },
  { id: '+243', label: '+243', countryName: 'Congo (Kinshasa)' },
  { id: '+244', label: '+244', countryName: 'Angola' },
  { id: '+245', label: '+245', countryName: 'Guinea-Bissau' },
  { id: '+246', label: '+246', countryName: 'British Indian Ocean Territory' },
  { id: '+247', label: '+247', countryName: 'Ascension Island' },
  { id: '+248', label: '+248', countryName: 'Seychelles' },
  { id: '+249', label: '+249', countryName: 'Sudan' },
  { id: '+250', label: '+250', countryName: 'Rwanda' },
  { id: '+251', label: '+251', countryName: 'Ethiopia' },
  { id: '+252', label: '+252', countryName: 'Somalia' },
  { id: '+253', label: '+253', countryName: 'Djibouti' },
  { id: '+254', label: '+254', countryName: 'Kenya' },
  { id: '+255', label: '+255', countryName: 'Tanzania' },
  { id: '+256', label: '+256', countryName: 'Uganda' },
  { id: '+257', label: '+257', countryName: 'Burundi' },
  { id: '+258', label: '+258', countryName: 'Mozambique' },
  { id: '+260', label: '+260', countryName: 'Zambia' },
  { id: '+261', label: '+261', countryName: 'Madagascar' },
  { id: '+262', label: '+262', countryName: 'Réunion' },
  { id: '+263', label: '+263', countryName: 'Zimbabwe' },
  { id: '+264', label: '+264', countryName: 'Namibia' },
  { id: '+265', label: '+265', countryName: 'Malawi' },
  { id: '+266', label: '+266', countryName: 'Lesotho' },
  { id: '+267', label: '+267', countryName: 'Botswana' },
  { id: '+268', label: '+268', countryName: 'Eswatini' },
  { id: '+269', label: '+269', countryName: 'Comoros' },
  { id: '+290', label: '+290', countryName: 'Saint Helena' },
  { id: '+291', label: '+291', countryName: 'Eritrea' },
  { id: '+297', label: '+297', countryName: 'Aruba' },
  { id: '+298', label: '+298', countryName: 'Faroe Islands' },
  { id: '+299', label: '+299', countryName: 'Greenland' }
];

export const visaType = [
  { id: 1, label: 'Citizen' },
  { id: 2, label: 'Permanent Resident' },
  { id: 3, label: 'Student Visa' },
  { id: 4, label: 'Temporary Visa' },
  { id: 5, label: 'Work Permit' }
]

export const ageRange = [
  { id: 18, label: '18 Years' },
  { id: 19, label: '19 Years' },
  { id: 20, label: '20 Years' },
  { id: 21, label: '21 Years' },
  { id: 22, label: '22 Years' },
  { id: 23, label: '23 Years' },
  { id: 24, label: '24 Years' },
  { id: 25, label: '25 Years' },
  { id: 26, label: '26 Years' },
  { id: 27, label: '27 Years' },
  { id: 28, label: '28 Years' },
  { id: 29, label: '29 Years' },
  { id: 30, label: '30 Years' },
  { id: 31, label: '31 Years' },
  { id: 32, label: '32 Years' },
  { id: 33, label: '33 Years' },
  { id: 34, label: '34 Years' },
  { id: 35, label: '35 Years' },
  { id: 36, label: '36 Years' },
  { id: 37, label: '37 Years' },
  { id: 38, label: '38 Years' },
  { id: 39, label: '39 Years' },
  { id: 40, label: '40 Years' },
  { id: 41, label: '41 Years' },
  { id: 42, label: '42 Years' },
  { id: 43, label: '43 Years' },
  { id: 44, label: '44 Years' },
  { id: 45, label: '45 Years' },
  { id: 46, label: '46 Years' },
  { id: 47, label: '47 Years' },
  { id: 48, label: '48 Years' },
  { id: 49, label: '49 Years' },
  { id: 50, label: '50 Years' },
  { id: 51, label: '51 Years' },
  { id: 52, label: '52 Years' },
  { id: 53, label: '53 Years' },
  { id: 54, label: '54 Years' },
  { id: 55, label: '55 Years' },
  { id: 56, label: '56 Years' },
  { id: 57, label: '57 Years' },
  { id: 58, label: '58 Years' },
  { id: 59, label: '59 Years' },
  { id: 60, label: '60 Years' }
]